### ISSUE TITLE
Disable sign up for grafana by default

### ISSUE THREAD

**Issue by sheerun** [deis/monitor#171]
Hey,

I've deployed deis to production and to my surprise, grafana allows for anyone to sign-up by default.. Is there any reason to do so? I'd suggest disabling it and allowing to enable by setting ALLOW_SIGN_UP="true" 

Thanks!

**Comment by bacongobbler** [comment]
This has already been exposed as ALLOW_SIGN_UP since the project's inception: https://github.com/deis/monitor/blob/master/grafana/rootfs/usr/share/grafana/grafana.ini.tpl#L150

You can set [ALLOW_SIGN_UP to false on the pod](https://deis.com/docs/workflow/managing-workflow/tuning-component-settings/) and it will take effect. Again, since this has already been set in stone we cannot break this due to backwards compatibility. Is there documentation missing somewhere that you require more clarification?

**Comment by sheerun** [comment]
@bacongobbler I explicitly wrote about this setting in description.. This issue is about making this `ALLOW_SIGN_UP=false` by default. Could you reopen?

**Comment by bacongobbler** [comment]
We cannot change settings in the v2 timeline. Similar to registration mode being open by default in the controller, this must stay as-is. We can make a note of it in the production settings docs though.

**Comment by jordan-thoms** [comment]
This is very confusing for new deis users - the Production Deployments page ( https://deis.com/docs/workflow/managing-workflow/production-deployments/ ) links to 'Customizing Monitor' ( https://deis.com/docs/workflow/managing-workflow/tuning-component-settings/#customizing-the-monitor ) for more information on disabling signups, but in the linked section it just says 'The monitor component uses Telegraf under the hood, and derives most of its configuration from it. Please see telegraf configuration for more information on tuning the Monitor component.' - With no reference to the ALLOW_SIGN_UP setting, or how we are supposed to set it.
As I understand it, that documentation is incorrect at any rate, since we need to change the setting within Grafana, not telegraf.

Given that this seems like  a security concern that 100% of deis production deployments would want to address , I think this should be clearly documented.

**Comment by jchauncey** [comment]
@jordan-thoms ive got a PR coming that updates the documentation for monitoring so I will make sure we update this section to describe how to turn off sign ups within grafana. I will also try and PR a change to make it easier to configure from the chart.
